# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-external-dns
  description: This component creates a Helm deployment for external-dns on a Kubernetes cluster
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




